#!/bin/bash

#PBS -l walltime=00:20:00,select=1:ncpus=1:mem=2gb
#PBS -N consensus_test
#PBS -M nicholas.mateyko@ubc.ca
#PBS -m abe
#PBS -A st-cdeboer-1
#PBS -o output.txt
#PBS -e error.txt

##############################################################

cd $PBS_O_WORKDIR
source /arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/miniconda3-4.6.14-f4hr756q34tvp7nsjn7hovq46fomaww6/etc/profile.d/conda.sh
conda activate plab
dataDir="/arc/project/st-cdeboer-1/nick/PlasmidLibraryAmplificationBias/data/trimmed"

/arc/project/st-cdeboer-1/nick/PlasmidLibraryAmplificationBias/scripts/consensus_reads.py -i1 $dataDir/trimmed.1.1.fastq.gz -i2 $dataDir/trimmed.2.1.fastq.gz -o consensus_test_out.txt.gz -l log.txt
