samples:
  liquid_1: CTTACCGG-TGAAGACG
  semisolid_1: TCAAGCCG-TTACGTGA
  bead_1: ATGCGGTG-TAGTCGTG
  small_plate_1: AGGTAACA-ACCTTCAT
  large_plate_1: ACTAGAGA-ATAAGCCA
  liquid_2: AAGGAGTG-CTGTTCAA
  semisolid_2: TGCATACA-TAAGCTAG
  bead_2: TGGCCTAC-TGCTTAGA
  small_plate_2: CCTCTTCT-CGAGAATA
  large_plate_2: CGAGGAAG-CAGTTGAT
  liquid_3: AGATAAGC-CCAAGCTT
  semisolid_3: TACTCGAA-TCGGATGA
  bead_3: TCACGAAG-CCTATCAA
  small_plate_3: TGGATTGC-ATGGAATG
  large_plate_3: ACGAACCT-TCAATCCA
  liquid_4: CAGTAGCT-CGCCATAA
  semisolid_4: CTTAACAC-TCCGCCTA
  bead_4: TTGTTGAG-AACCGCGT
  small_plate_4: TCCGTGTT-AGGCATCT
  large_plate_4: CTGTCTAT-CCTTAGAT
  input_1: CGTTAATC-TAACTTGG
  input_2: TACGTGCA-CAATGACG
  input_3: TTACAGAG-CTGGCACT
  input_4: CAAGCGAG-AAGCCGAA
