#!/bin/bash
#PBS -l walltime=1:00:00,select=1:ncpus=1:mem=4gb
#PBS -J 1-10
#PBS -N cutadapt_plab
#PBS -M nicholas.mateyko@ubc.ca
#PBS -m abe
#PBS -A st-cdeboer-1
#PBS -o output_^array_index^.txt
#PBS -e error_^array_index^.txt
 
################################################################################
 
cd $PBS_O_WORKDIR
source /arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/miniconda3-4.6.14-f4hr756q34tvp7nsjn7hovq46fomaww6/etc/profile.d/conda.sh
conda activate cutadaptenv

set -e
logDir="log"
dataDir="/arc/project/st-cdeboer-1/nick/PlasmidLibraryAmplificationBias/data"
idx=$PBS_ARRAY_INDEX
mkdir -p log 

if [ ! -e $logDir/$idx.cutadapt.done ]
then
        cutadapt --untrimmed-o untrimmed1.$idx.fastq.gz --untrimmed-p untrimmed2.$idx.fastq.gz -m 80 --too-short-o short1.$idx.fastq.gz --too-short-p short2.$idx.fastq.gz \
        -M 80 --too-long-o long1.$idx.fastq.gz --too-long-p long2.$idx.fastq.gz -a ^TGCATTTTTTTCACATC...GGTTACGGCTGTT -A ^AACAGCCGTAACC...GATGTGAAAAAAATGCA \
         -o trimmed.1.$idx.fastq.gz -p trimmed.2.$idx.fastq.gz $dataDir/PLAB_${idx}_read1.fastq.gz $dataDir/PLAB_${idx}_read2.fastq.gz
        
        touch $logDir/$idx.cutadapt.done
else
        echo Already performed cutadapt of $idx
fi